### ISSUE TITLE
b

### ISSUE THREAD

**Issue by sotetsuk** [sotetsuk/travis-redpen-test#4]
# Issue①の番号
# 締切

締切 xx/xx （勉強会7日前。勉強会が水曜なら前の週の水曜一杯）
# TODO
- [ ] ブランチとプルリクをつくりアサインを自分にする（ブランチ名: `pXX-pXX-move-from-origin`）
- [ ] オリジナルの原稿を貼り付けてコミット e.g., [commit example](https://github.com/sotetsuk/algo-rl-ja/pull/29/commits/b0ee68d926018fd1935c02ae09bab4fac9426963)
  - 原著はこちらのブランチから: https://github.com/sotetsuk/algo-rl-ja/tree/en-original
- [ ] コンパイルが通るように必要なファイルを修正してコミット e.g., [commit example](https://github.com/sotetsuk/algo-rl-ja/issues/2)
  - 例えば `\iflong ... \fi`, `\TODO`, `\note` あたりの不要コマンドは消す（`\iflong`の中身はpdfに残るので中身は残す）
  - そのままでコンパイルが通らなければ `commands.tex` に加筆する
  - 元々の原稿でコメントアウトされてる部分は消してしまう（著者が見られたくないかもしれないし、紛らわしい）
- [ ] 数式、図等以外の全ての文章をコメントアウトしてコミット e.g., [commit example](https://github.com/sotetsuk/algo-rl-ja/pull/29/commits/d99474f60f59968e96ac73f896fd4b152d37d356)
- [ ] 原文を一文ごとに区切ってコミット e.g., [commit example](https://github.com/sotetsuk/algo-rl-ja/pull/29/commits/d99474f60f59968e96ac73f896fd4b152d37d356)
- [ ] ShareLatexから粗訳を移してコミット e.g., [commit example](https://github.com/sotetsuk/algo-rl-ja/pull/29/commits/5359227af3a3f3439c369d24ee03855fb510d9ee)
- [ ] 文中の数式、引用等をすべて原著のものに合わせてコミット
- [ ] @sotetsukにアサインを変更してslackで@sotetsukに連絡
- [ ] @sotetsukが確認の上マージ
